CREATE TABLE users (user_id VARCHAR(36) PRIMARY KEY, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, slack_id VARCHAR(64) NOT NULL UNIQUE, email VARCHAR(255) NOT NULL UNIQUE, is_admin BOOLEAN NOT NULL DEFAULT FALSE, is_reviewer BOOLEAN NOT NULL DEFAULT FALSE, address_line_1 VARCHAR(255), address_line_2 VARCHAR(255), city VARCHAR(100), state VARCHAR(100), country VARCHAR(100), post_code VARCHAR(20), birthday TIMESTAMP WITH TIME ZONE, dates_logged_in JSON, created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP); CREATE INDEX idx_users_user_id ON users(user_id); CREATE INDEX idx_users_slack_id ON users(slack_id); CREATE INDEX idx_users_email ON users(email); CREATE TABLE projects (project_id VARCHAR(36) PRIMARY KEY, user_id VARCHAR(36) NOT NULL, project_name VARCHAR(200) NOT NULL, project_description TEXT NOT NULL, attachment_urls JSON, code_url VARCHAR(500), live_url VARCHAR(500), submission_week VARCHAR(50) NOT NULL, paper_url VARCHAR(500), shipped BOOLEAN NOT NULL DEFAULT FALSE, sent_to_airtable BOOLEAN NOT NULL DEFAULT FALSE, review_ids JSON, time_spent INTEGER, created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(user_id)); CREATE INDEX idx_projects_project_id ON projects(project_id); CREATE INDEX idx_projects_user_id ON projects(user_id); CREATE TABLE reviews (review_id VARCHAR(36) PRIMARY KEY, reviewer_user_id VARCHAR(36) NOT NULL, project_id VARCHAR(36) NOT NULL, review_comments TEXT NOT NULL, review_decision VARCHAR(50) NOT NULL, review_timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (reviewer_user_id) REFERENCES users(user_id), FOREIGN KEY (project_id) REFERENCES projects(project_id)); CREATE INDEX idx_reviews_review_id ON reviews(review_id); CREATE INDEX idx_reviews_reviewer_user_id ON reviews(reviewer_user_id); CREATE INDEX idx_reviews_project_id ON reviews(project_id); CREATE TABLE votes (vote_id VARCHAR(36) PRIMARY KEY, user_id VARCHAR(36) NOT NULL, project_id VARCHAR(36) NOT NULL, vote_ranking INTEGER NOT NULL, timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(user_id), FOREIGN KEY (project_id) REFERENCES projects(project_id)); CREATE INDEX idx_votes_vote_id ON votes(vote_id); CREATE INDEX idx_votes_user_id ON votes(user_id); CREATE INDEX idx_votes_project_id ON votes(project_id);

CREATE TABLE rsvps (
    email VARCHAR(255) PRIMARY KEY,
    ip_address VARCHAR(45) NOT NULL,
    rsvptime TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_rsvps_email ON rsvps(email);
CREATE INDEX idx_rsvps_ip ON rsvps(ip_address);
