"""auto_migration

Revision ID: 124f5c6fd951
Revises: 4cd23121b22f
Create Date: 2025-11-23 07:46:46.901677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '124f5c6fd951'
down_revision: Union[str, Sequence[str], None] = '4cd23121b22f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET is_public = false")
    op.alter_column('users', 'is_public', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_public')
    # ### end Alembic commands ###
