"""add_handle_to_user

Revision ID: 4ec9aa20b609
Revises: d9aed0d2f684
Create Date: 2025-11-23 07:40:59.324503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ec9aa20b609'
down_revision: Union[str, Sequence[str], None] = 'd9aed0d2f684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hackatime_projects_id'), table_name='hackatime_projects')
    op.drop_index(op.f('ix_hackatime_projects_user_id'), table_name='hackatime_projects')
    op.drop_table('hackatime_projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hackatime_projects',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('seconds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('hackatime_projects_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('hackatime_projects_pkey'))
    )
    op.create_index(op.f('ix_hackatime_projects_user_id'), 'hackatime_projects', ['user_id'], unique=False)
    op.create_index(op.f('ix_hackatime_projects_id'), 'hackatime_projects', ['id'], unique=False)
    # ### end Alembic commands ###
