"""auto_migration

Revision ID: 796408a85901
Revises: 4c06f9a4ef2e
Create Date: 2025-12-05 11:36:10.357570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '796408a85901'
down_revision: Union[str, Sequence[str], None] = '4c06f9a4ef2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('event', sa.String(length=50), nullable=False),
    sa.Column('slide', sa.Integer(), nullable=True),
    sa.Column('total_slides', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_events_id'), 'onboarding_events', ['id'], unique=False)
    op.create_index(op.f('ix_onboarding_events_user_id'), 'onboarding_events', ['user_id'], unique=False)
    op.add_column('users', sa.Column('handle', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('assigned_author_id', sa.String(length=36), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('public_profile_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(length=1000), nullable=True))
    op.alter_column('users', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_users_assigned_author_id'), 'users', ['assigned_author_id'], unique=False)
    op.create_index(op.f('ix_users_handle'), 'users', ['handle'], unique=True)
    op.create_index(op.f('ix_users_public_profile_url'), 'users', ['public_profile_url'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_foreign_key(None, 'users', 'users', ['assigned_author_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_public_profile_url'), table_name='users')
    op.drop_index(op.f('ix_users_handle'), table_name='users')
    op.drop_index(op.f('ix_users_assigned_author_id'), table_name='users')
    op.alter_column('users', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('users', 'bio')
    op.drop_column('users', 'public_profile_url')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'assigned_author_id')
    op.drop_column('users', 'role')
    op.drop_column('users', 'handle')
    op.drop_index(op.f('ix_onboarding_events_user_id'), table_name='onboarding_events')
    op.drop_index(op.f('ix_onboarding_events_id'), table_name='onboarding_events')
    op.drop_table('onboarding_events')
    # ### end Alembic commands ###
