"""auto_migration

Revision ID: 843f222ad642
Revises: 476fc7ec99e1
Create Date: 2025-12-01 15:10:33.709636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '843f222ad642'
down_revision: Union[str, Sequence[str], None] = '476fc7ec99e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hackatime_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hackatime_projects_id'), 'hackatime_projects', ['id'], unique=False)
    op.create_index(op.f('ix_hackatime_projects_user_id'), 'hackatime_projects', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hackatime_projects_user_id'), table_name='hackatime_projects')
    op.drop_index(op.f('ix_hackatime_projects_id'), table_name='hackatime_projects')
    op.drop_table('hackatime_projects')
    # ### end Alembic commands ###
