"""auto_migration

Revision ID: 86d6b6532536
Revises: 124f5c6fd951
Create Date: 2025-12-01 15:08:52.436277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86d6b6532536'
down_revision: Union[str, Sequence[str], None] = '124f5c6fd951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('public_profile_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(length=1000), nullable=True))
    op.create_index(op.f('ix_users_public_profile_url'), 'users', ['public_profile_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_public_profile_url'), table_name='users')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'public_profile_url')
    # ### end Alembic commands ###
