"""auto_migration

Revision ID: 8c4686009abf
Revises: 9a4e89082f9e
Create Date: 2025-12-09 16:21:15.661383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c4686009abf'
down_revision: Union[str, Sequence[str], None] = '9a4e89082f9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_type', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('github_installation_id', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('github_repo_path', sa.String(length=200), nullable=True))
    op.add_column('projects', sa.Column('hackatime_projects', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('projects', sa.Column('hackatime_hours', sa.Float(), nullable=True))
    op.drop_index(op.f('idx_projects_project_id'), table_name='projects')
    op.drop_index(op.f('idx_projects_user_id'), table_name='projects')
    op.create_index(op.f('ix_projects_project_id'), 'projects', ['project_id'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.drop_column('projects', 'review_ids')
    op.drop_index(op.f('idx_reviews_project_id'), table_name='reviews')
    op.drop_index(op.f('idx_reviews_review_id'), table_name='reviews')
    op.drop_index(op.f('idx_reviews_reviewer_user_id'), table_name='reviews')
    op.create_index(op.f('ix_reviews_project_id'), 'reviews', ['project_id'], unique=False)
    op.create_index(op.f('ix_reviews_review_id'), 'reviews', ['review_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewer_user_id'), 'reviews', ['reviewer_user_id'], unique=False)
    op.drop_index(op.f('idx_rsvps_email'), table_name='rsvps')
    op.drop_index(op.f('idx_rsvps_ip'), table_name='rsvps')
    op.create_index(op.f('ix_rsvps_email'), 'rsvps', ['email'], unique=False)
    op.create_index(op.f('ix_rsvps_ip_address'), 'rsvps', ['ip_address'], unique=False)
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('handle', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('referral_code', sa.String(length=8), nullable=False))
    op.add_column('users', sa.Column('referred_by_user_id', sa.String(length=36), nullable=True))
    op.add_column('users', sa.Column('storyline_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('hackatime_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('slack_linked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('idv_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('identity_vault_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('identity_vault_access_token', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('idv_country', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('verification_status', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('ysws_eligible', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'slack_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_slack_id'), table_name='users')
    op.drop_index(op.f('idx_users_user_id'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_slack_id_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_handle'), 'users', ['handle'], unique=True)
    op.create_index(op.f('ix_users_identity_vault_id'), 'users', ['identity_vault_id'], unique=True)
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.create_index(op.f('ix_users_referred_by_user_id'), 'users', ['referred_by_user_id'], unique=False)
    op.create_index(op.f('ix_users_slack_id'), 'users', ['slack_id'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_foreign_key(None, 'users', 'users', ['referred_by_user_id'], ['user_id'])
    op.drop_column('users', 'address_line_1')
    op.drop_column('users', 'country')
    op.drop_column('users', 'address_line_2')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'birthday')
    op.drop_column('users', 'city')
    op.drop_column('users', 'is_reviewer')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'state')
    op.drop_column('users', 'dates_logged_in')
    op.drop_column('users', 'post_code')
    op.drop_index(op.f('idx_votes_project_id'), table_name='votes')
    op.drop_index(op.f('idx_votes_user_id'), table_name='votes')
    op.drop_index(op.f('idx_votes_vote_id'), table_name='votes')
    op.create_index(op.f('ix_votes_project_id'), 'votes', ['project_id'], unique=False)
    op.create_index(op.f('ix_votes_user_id'), 'votes', ['user_id'], unique=False)
    op.create_index(op.f('ix_votes_vote_id'), 'votes', ['vote_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_vote_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_user_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_project_id'), table_name='votes')
    op.create_index(op.f('idx_votes_vote_id'), 'votes', ['vote_id'], unique=False)
    op.create_index(op.f('idx_votes_user_id'), 'votes', ['user_id'], unique=False)
    op.create_index(op.f('idx_votes_project_id'), 'votes', ['project_id'], unique=False)
    op.add_column('users', sa.Column('post_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('dates_logged_in', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_reviewer', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('birthday', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('address_line_2', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('address_line_1', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_slack_id'), table_name='users')
    op.drop_index(op.f('ix_users_referred_by_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_identity_vault_id'), table_name='users')
    op.drop_index(op.f('ix_users_handle'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_slack_id_key'), 'users', ['slack_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('idx_users_slack_id'), 'users', ['slack_id'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'slack_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('users', 'onboarding_completed_at')
    op.drop_column('users', 'ysws_eligible')
    op.drop_column('users', 'verification_status')
    op.drop_column('users', 'idv_country')
    op.drop_column('users', 'identity_vault_access_token')
    op.drop_column('users', 'identity_vault_id')
    op.drop_column('users', 'idv_completed_at')
    op.drop_column('users', 'slack_linked_at')
    op.drop_column('users', 'hackatime_completed_at')
    op.drop_column('users', 'storyline_completed_at')
    op.drop_column('users', 'referred_by_user_id')
    op.drop_column('users', 'referral_code')
    op.drop_column('users', 'handle')
    op.drop_column('users', 'phone_number')
    op.drop_index(op.f('ix_rsvps_ip_address'), table_name='rsvps')
    op.drop_index(op.f('ix_rsvps_email'), table_name='rsvps')
    op.create_index(op.f('idx_rsvps_ip'), 'rsvps', ['ip_address'], unique=False)
    op.create_index(op.f('idx_rsvps_email'), 'rsvps', ['email'], unique=False)
    op.drop_index(op.f('ix_reviews_reviewer_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_review_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_project_id'), table_name='reviews')
    op.create_index(op.f('idx_reviews_reviewer_user_id'), 'reviews', ['reviewer_user_id'], unique=False)
    op.create_index(op.f('idx_reviews_review_id'), 'reviews', ['review_id'], unique=False)
    op.create_index(op.f('idx_reviews_project_id'), 'reviews', ['project_id'], unique=False)
    op.add_column('projects', sa.Column('review_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_id'), table_name='projects')
    op.create_index(op.f('idx_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_index(op.f('idx_projects_project_id'), 'projects', ['project_id'], unique=False)
    op.drop_column('projects', 'hackatime_hours')
    op.drop_column('projects', 'hackatime_projects')
    op.drop_column('projects', 'github_repo_path')
    op.drop_column('projects', 'github_installation_id')
    op.drop_column('projects', 'project_type')
    # ### end Alembic commands ###
