"""auto_migration

Revision ID: a1396f016c3b
Revises: 5786786c66e5
Create Date: 2025-11-22 20:42:20.326706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1396f016c3b'
down_revision: Union[str, Sequence[str], None] = '5786786c66e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hackatime_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hackatime_projects_id'), 'hackatime_projects', ['id'], unique=False)
    op.create_index(op.f('ix_hackatime_projects_user_id'), 'hackatime_projects', ['user_id'], unique=False)
    op.add_column('projects', sa.Column('hackatime_project_keys', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'hackatime_project_keys')
    op.drop_index(op.f('ix_hackatime_projects_user_id'), table_name='hackatime_projects')
    op.drop_index(op.f('ix_hackatime_projects_id'), table_name='hackatime_projects')
    op.drop_table('hackatime_projects')
    # ### end Alembic commands ###
