"""auto_migration

Revision ID: afe9408d66b0
Revises: 67539c76e503
Create Date: 2025-12-08 10:04:00.915964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afe9408d66b0'
down_revision: Union[str, Sequence[str], None] = '67539c76e503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_status', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('ysws_eligible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ysws_eligible')
    op.drop_column('users', 'verification_status')
    # ### end Alembic commands ###
