"""auto_migration

Revision ID: b1639e2cf5fe
Revises: a01bdef9447b
Create Date: 2025-12-05 11:09:04.290339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import secrets
import string

# revision identifiers, used by Alembic.
revision: str = 'b1639e2cf5fe'
down_revision: Union[str, Sequence[str], None] = 'a01bdef9447b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onboarding_events_id'), table_name='onboarding_events')
    op.drop_index(op.f('ix_onboarding_events_user_id'), table_name='onboarding_events')
    op.drop_table('onboarding_events')
    op.drop_column('projects', 'github_installation_id')
    op.drop_column('projects', 'github_repo_path')
    op.add_column('users', sa.Column('referral_code', sa.String(length=8), nullable=True))
    op.add_column('users', sa.Column('referred_by', sa.String(length=8), nullable=True))
    
    # Generate referral codes for existing users
    connection = op.get_bind()
    users = connection.execute(sa.text("SELECT user_id FROM users WHERE referral_code IS NULL")).fetchall()
    for user in users:
        code = ''.join(secrets.choice(string.ascii_uppercase + string.digits) for _ in range(8))
        connection.execute(sa.text("UPDATE users SET referral_code = :code WHERE user_id = :user_id"), {"code": code, "user_id": user[0]})
    
    # Now make it NOT NULL
    op.alter_column('users', 'referral_code', nullable=False)
    op.drop_index(op.f('ix_users_assigned_author_id'), table_name='users')
    op.drop_index(op.f('ix_users_handle'), table_name='users')
    op.drop_index(op.f('ix_users_public_profile_url'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.drop_constraint(op.f('fk_users_assigned_author_id'), 'users', type_='foreignkey')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'role')
    op.drop_column('users', 'assigned_author_id')
    op.drop_column('users', 'public_profile_url')
    op.drop_column('users', 'is_public')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'handle')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('handle', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('bio', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('public_profile_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('assigned_author_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_users_assigned_author_id'), 'users', 'users', ['assigned_author_id'], ['user_id'])
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_public_profile_url'), 'users', ['public_profile_url'], unique=True)
    op.create_index(op.f('ix_users_handle'), 'users', ['handle'], unique=True)
    op.create_index(op.f('ix_users_assigned_author_id'), 'users', ['assigned_author_id'], unique=False)
    op.drop_column('users', 'referred_by')
    op.drop_column('users', 'referral_code')
    op.add_column('projects', sa.Column('github_repo_path', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('github_installation_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_table('onboarding_events',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('event', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('slide', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_slides', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('onboarding_events_pkey'))
    )
    op.create_index(op.f('ix_onboarding_events_user_id'), 'onboarding_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_onboarding_events_id'), 'onboarding_events', ['id'], unique=False)
    # ### end Alembic commands ###
