"""auto_migration

Revision ID: c80c9c2d586d
Revises: 8c4686009abf
Create Date: 2025-12-12 16:50:54.450463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c80c9c2d586d'
down_revision: Union[str, Sequence[str], None] = '8c4686009abf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_utms_utm_source'), table_name='utms')
    op.create_index(op.f('ix_utms_utm_source'), 'utms', ['utm_source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_utms_utm_source'), table_name='utms')
    op.create_index(op.f('idx_utms_utm_source'), 'utms', ['utm_source'], unique=False)
    # ### end Alembic commands ###
