"""auto_migration

Revision ID: d9aed0d2f684
Revises: 4e18c15004df
Create Date: 2025-11-23 07:40:47.985693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9aed0d2f684'
down_revision: Union[str, Sequence[str], None] = '4e18c15004df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('handle', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_users_handle'), 'users', ['handle'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_handle'), table_name='users')
    op.drop_column('users', 'handle')
    # ### end Alembic commands ###
