"""Initial migration

Revision ID: eaab3c49fdb0
Revises: 
Create Date: 2025-11-22 10:03:32.933749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaab3c49fdb0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_type', sa.String(length=50), nullable=True))
    op.drop_index(op.f('idx_projects_project_id'), table_name='projects')
    op.drop_index(op.f('idx_projects_user_id'), table_name='projects')
    op.create_index(op.f('ix_projects_project_id'), 'projects', ['project_id'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.drop_index(op.f('idx_reviews_project_id'), table_name='reviews')
    op.drop_index(op.f('idx_reviews_review_id'), table_name='reviews')
    op.drop_index(op.f('idx_reviews_reviewer_user_id'), table_name='reviews')
    op.create_index(op.f('ix_reviews_project_id'), 'reviews', ['project_id'], unique=False)
    op.create_index(op.f('ix_reviews_review_id'), 'reviews', ['review_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewer_user_id'), 'reviews', ['reviewer_user_id'], unique=False)
    op.drop_index(op.f('idx_rsvps_email'), table_name='rsvps')
    op.drop_index(op.f('idx_rsvps_ip'), table_name='rsvps')
    op.create_index(op.f('ix_rsvps_email'), 'rsvps', ['email'], unique=False)
    op.create_index(op.f('ix_rsvps_ip_address'), 'rsvps', ['ip_address'], unique=False)
    op.drop_column('rsvps', 'referral_sent')
    op.drop_column('rsvps', 'age')
    op.drop_column('rsvps', 'image')
    op.add_column('users', sa.Column('is_idv', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_slack_member', sa.Boolean(), nullable=False))
    op.alter_column('users', 'slack_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_slack_id'), table_name='users')
    op.drop_index(op.f('idx_users_user_id'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_slack_id_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_slack_id'), 'users', ['slack_id'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.drop_index(op.f('idx_votes_project_id'), table_name='votes')
    op.drop_index(op.f('idx_votes_user_id'), table_name='votes')
    op.drop_index(op.f('idx_votes_vote_id'), table_name='votes')
    op.create_index(op.f('ix_votes_project_id'), 'votes', ['project_id'], unique=False)
    op.create_index(op.f('ix_votes_user_id'), 'votes', ['user_id'], unique=False)
    op.create_index(op.f('ix_votes_vote_id'), 'votes', ['vote_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_vote_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_user_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_project_id'), table_name='votes')
    op.create_index(op.f('idx_votes_vote_id'), 'votes', ['vote_id'], unique=False)
    op.create_index(op.f('idx_votes_user_id'), 'votes', ['user_id'], unique=False)
    op.create_index(op.f('idx_votes_project_id'), 'votes', ['project_id'], unique=False)
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_slack_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_slack_id_key'), 'users', ['slack_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('idx_users_slack_id'), 'users', ['slack_id'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'slack_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('users', 'is_slack_member')
    op.drop_column('users', 'is_idv')
    op.add_column('rsvps', sa.Column('image', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('rsvps', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('rsvps', sa.Column('referral_sent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_rsvps_ip_address'), table_name='rsvps')
    op.drop_index(op.f('ix_rsvps_email'), table_name='rsvps')
    op.create_index(op.f('idx_rsvps_ip'), 'rsvps', ['ip_address'], unique=False)
    op.create_index(op.f('idx_rsvps_email'), 'rsvps', ['email'], unique=False)
    op.drop_index(op.f('ix_reviews_reviewer_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_review_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_project_id'), table_name='reviews')
    op.create_index(op.f('idx_reviews_reviewer_user_id'), 'reviews', ['reviewer_user_id'], unique=False)
    op.create_index(op.f('idx_reviews_review_id'), 'reviews', ['review_id'], unique=False)
    op.create_index(op.f('idx_reviews_project_id'), 'reviews', ['project_id'], unique=False)
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_id'), table_name='projects')
    op.create_index(op.f('idx_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_index(op.f('idx_projects_project_id'), 'projects', ['project_id'], unique=False)
    op.drop_column('projects', 'project_type')
    # ### end Alembic commands ###
