"""auto_migration

Revision ID: edee474f5899
Revises: 001_initial
Create Date: 2025-12-06 16:54:32.173311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = 'edee474f5899'
down_revision: Union[str, Sequence[str], None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def column_exists(table_name: str, column_name: str) -> bool:
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade() -> None:
    """Upgrade schema."""
    if not column_exists('users', 'storyline_completed_at'):
        op.add_column('users', sa.Column('storyline_completed_at', sa.DateTime(timezone=True), nullable=True))
    if not column_exists('users', 'hackatime_completed_at'):
        op.add_column('users', sa.Column('hackatime_completed_at', sa.DateTime(timezone=True), nullable=True))
    if not column_exists('users', 'slack_linked_at'):
        op.add_column('users', sa.Column('slack_linked_at', sa.DateTime(timezone=True), nullable=True))
    if not column_exists('users', 'idv_completed_at'):
        op.add_column('users', sa.Column('idv_completed_at', sa.DateTime(timezone=True), nullable=True))
    if not column_exists('users', 'onboarding_completed_at'):
        op.add_column('users', sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_completed_at')
    op.drop_column('users', 'idv_completed_at')
    op.drop_column('users', 'slack_linked_at')
    op.drop_column('users', 'hackatime_completed_at')
    op.drop_column('users', 'storyline_completed_at')
    # ### end Alembic commands ###
