"""auto_migration

Revision ID: edee474f5899
Revises: 001_initial
Create Date: 2025-12-06 16:54:32.173311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edee474f5899'
down_revision: Union[str, Sequence[str], None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('storyline_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('hackatime_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('slack_linked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('idv_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_completed_at')
    op.drop_column('users', 'idv_completed_at')
    op.drop_column('users', 'slack_linked_at')
    op.drop_column('users', 'hackatime_completed_at')
    op.drop_column('users', 'storyline_completed_at')
    # ### end Alembic commands ###
